export const SITUATIONS = [
  { id: "twisted", emoji: "🦶", label: "Twisted / Sprained", supported: true, desc: "Ankle, wrist or joint twist" },
  { id: "hit", emoji: "🤕", label: "Got hit", supported: true, desc: "Impact, knock or bruise" },
  { id: "cut", emoji: "🩸", label: "Minor cut", supported: true, desc: "Scrape, cut or bleeding" },
  { id: "burn", emoji: "🔥", label: "Minor burn", supported: true, desc: "Cooking or hot-surface burn" },
  { id: "sting", emoji: "🐝", label: "Sting / bite", supported: true, desc: "Insect sting or minor bite" },
  { id: "medical", emoji: "🚑", label: "Need medical help", supported: true, ambulance: true, desc: "Escalate to an ambulance" },
];

export const KITS = {
  twisted: {
    id: "twisted",
    situationLabel: "Twisted / Sprained",
    name: "FirstHour — Ankle First-Aid Kit",
    tagline: "The right first aid, for the first hour.",
    emoji: "🦶",
    price: 149,
    eta: 10,
    contents: [
      "Instant cold pack",
      "Ankle compression wrap",
      "Protective barrier layer for cold application",
      "Visual instruction card",
      "QR code linking to short usage instructions",
      "Red-flag guidance card",
    ],
    addons: [
      { id: "gel", name: "Reusable gel cold pack", price: 89, emoji: "🧊" },
      { id: "tape", name: "Skin-safe medical tape", price: 49, emoji: "🩹" },
      { id: "elevate", name: "Elevation foam wedge", price: 129, emoji: "🛏️" },
      { id: "support", name: "Rigid ankle support brace", price: 199, emoji: "🦵" },
    ],
    redFlags: [
      "Severe pain that does not reduce",
      "Visible deformity or bone out of place",
      "Significant bleeding or numbness",
      "Inability to bear any weight",
    ],
    tips: [
      "Do not apply the cold pack directly to bare skin — use the barrier layer.",
      "Do not wrap the compression wrap excessively tight.",
      "Stop using the product if symptoms worsen.",
      "Seek professional medical care if red-flag symptoms appear.",
    ],
  },
  hit: {
    id: "hit",
    situationLabel: "Got hit",
    name: "FirstHour — Impact Relief Kit",
    tagline: "Fast relief for knocks, bumps and bruises.",
    emoji: "🤕",
    price: 159,
    eta: 10,
    contents: [
      "Instant cold pack",
      "Compression wrap for swelling",
      "Protective barrier layer for cold application",
      "Bruise-relief gel sachet",
      "Visual instruction card",
      "QR code linking to short usage instructions",
      "Red-flag guidance card",
    ],
    addons: [
      { id: "gel", name: "Reusable gel cold pack", price: 89, emoji: "🧊" },
      { id: "spray", name: "Pain-relief spray", price: 129, emoji: "🧴" },
      { id: "wrap", name: "Extra compression wrap", price: 59, emoji: "🩹" },
      { id: "balm", name: "Muscle balm tube", price: 149, emoji: "🧪" },
    ],
    redFlags: [
      "Hit to the head with confusion, vomiting or drowsiness",
      "Loss of consciousness, even briefly",
      "Severe swelling or visible deformity",
      "Difficulty breathing after a chest or back impact",
    ],
    tips: [
      "Apply cold for 15–20 minutes at a time — never directly on bare skin.",
      "Rest the injured area and avoid pressure on it.",
      "Watch the area for 24 hours — swelling should ease, not grow.",
      "Seek professional medical care if red-flag symptoms appear.",
    ],
  },
  cut: {
    id: "cut",
    situationLabel: "Minor cut",
    name: "FirstHour — Cut & Bleed Kit",
    tagline: "Clean, close and cover — in minutes.",
    emoji: "🩸",
    price: 139,
    eta: 10,
    contents: [
      "Sterile gauze pads",
      "Antiseptic cleaning wipe",
      "Waterproof adhesive bandages (assorted)",
      "Butterfly closure strips",
      "Visual instruction card",
      "QR code linking to short usage instructions",
      "Red-flag guidance card",
    ],
    addons: [
      { id: "gauze", name: "Extra gauze & dressing pack", price: 79, emoji: "🧻" },
      { id: "liquid", name: "Liquid bandage seal", price: 99, emoji: "🧴" },
      { id: "gloves", name: "Nitrile gloves (pair)", price: 29, emoji: "🧤" },
      { id: "tape", name: "First-aid tape roll", price: 49, emoji: "🩹" },
    ],
    redFlags: [
      "Bleeding does not stop after 10 minutes of firm pressure",
      "The wound is deep, wide or the edges gape open",
      "A foreign object is embedded in the wound",
      "Warmth, pus or red streaks around the wound (infection)",
    ],
    tips: [
      "Wash your hands before touching the wound.",
      "Clean the wound with water, then apply firm pressure with clean gauze.",
      "Do not remove an embedded object — stabilise it and seek care.",
      "Change the dressing daily and keep the wound dry.",
    ],
  },
  burn: {
    id: "burn",
    situationLabel: "Minor burn",
    name: "FirstHour — Burn Relief Kit",
    tagline: "Cool, soothe and protect burned skin.",
    emoji: "🔥",
    price: 149,
    eta: 10,
    contents: [
      "Sterile non-stick burn dressing",
      "Cooling burn gel sachets",
      "Low-adherent padding layer",
      "Visual instruction card",
      "QR code linking to short usage instructions",
      "Red-flag guidance card",
    ],
    addons: [
      { id: "gel", name: "Extra burn gel sachets", price: 89, emoji: "🧴" },
      { id: "wrap", name: "Sterile cling wrap roll", price: 49, emoji: "📦" },
      { id: "fingers", name: "Individual finger dressings", price: 69, emoji: "🩹" },
      { id: "aloe", name: "Aloe soothing gel tube", price: 99, emoji: "🌿" },
    ],
    redFlags: [
      "Burn larger than your palm or with deep blistering",
      "Burns on the face, hands, feet or over joints",
      "White, leathery or charred skin — seek emergency care",
      "Chemical or electrical burn",
    ],
    tips: [
      "Cool the burn under running water for 20 minutes first.",
      "Never use ice, butter or toothpaste on a burn.",
      "Do not pop blisters — they protect the skin.",
      "Cover loosely with the non-stick dressing.",
    ],
  },
  sting: {
    id: "sting",
    situationLabel: "Sting / bite",
    name: "FirstHour — Sting & Bite Kit",
    tagline: "Remove, soothe and watch for reactions.",
    emoji: "🐝",
    price: 99,
    eta: 10,
    contents: [
      "Sting-relief wipe (antiseptic + anaesthetic)",
      "Precision tweezer for sting removal",
      "Soothing hydrocortisone sachet",
      "Instant cold compress sachet",
      "Visual instruction card",
      "QR code linking to short usage instructions",
      "Red-flag guidance card",
    ],
    addons: [
      { id: "antihist", name: "Antihistamine tablet strip", price: 59, emoji: "💊" },
      { id: "cold", name: "Extra cold compress sachets", price: 49, emoji: "🧊" },
      { id: "balm", name: "Itch-relief balm tube", price: 79, emoji: "🧴" },
      { id: "gloves", name: "Nitrile gloves (pair)", price: 29, emoji: "🧤" },
    ],
    redFlags: [
      "Difficulty breathing or swelling of lips and tongue — call emergency services now",
      "Hives or dizziness spreading beyond the sting site",
      "Sting inside the mouth or throat",
      "Signs of infection after 24–48 hours",
    ],
    tips: [
      "Remove the sting by scraping sideways — never squeeze it.",
      "Wash the area and apply a cold compress.",
      "Watch for 30 minutes for any allergic reaction.",
      "Seek professional medical care if red-flag symptoms appear.",
    ],
  },
};

export const getKit = (situationId) => KITS[situationId] || KITS.twisted;

export const ORDER_FLOW = [
  { key: "placed", label: "Order placed", emoji: "✅" },
  { key: "packed", label: "Kit packed", emoji: "📦" },
  { key: "out_for_delivery", label: "Out for delivery", emoji: "🛵" },
  { key: "delivered", label: "Delivered", emoji: "🎉" },
];

export const AMBULANCE_FLOW = [
  { key: "confirmed", label: "Booking confirmed", emoji: "✅" },
  { key: "assigned", label: "Ambulance assigned", emoji: "🚑" },
  { key: "on_the_way", label: "On the way", emoji: "🚦" },
  { key: "arrived", label: "Arrived", emoji: "📍" },
];